# Generated by Django 3.2.4 on 2021-07-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.FloatField(default=0.0, verbose_name='Prix')),
                ('images', models.ImageField(upload_to='photos/produits')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categorie')),
            ],
        ),
    ]
