# Generated by Django 3.2.4 on 2021-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='Prénom')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Pseudo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Téléphone')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date inscription')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Dernière connexion')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Super Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
