# Generated by Django 3.2.4 on 2021-07-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
    ]
