# Generated by Django 3.2.4 on 2021-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_pizza',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
